### ISSUE TITLE
Explicit .close() for the socket

### ISSUE THREAD

**Issue by msiebuhr** [msiebuhr/node-statsd-client#2]
When batch-programs are done, it would be nicer to call a `.close()` to close the socket and kill the timer, rather than having to wait ~1½ cycles of the timer for the program to end.

**Comment by zyf0330** [comment]
I want to send `gauge` metric when exit application. But after `gauge, close, process.exit`, it is not sent successfully. I must wait a while after `close`. I think `close` should return a `Promise`.
