### ISSUE TITLE
Middleware with timeByUrl path is not being parsed correctly

### ISSUE THREAD

**Issue by lumberj** [msiebuhr/node-statsd-client#52]
Debug output from statsd server:

```
1 Nov 14:12:46 - DEBUG: prefix.[object Object].response_time:3132|ms
```

This is how I'm using the module:

```
'use strict';

const SDC = require('statsd-client');
const sdc = new SDC({debug: true, prefix: 'prefix'});

sdc.increment('working');

const metricsMiddleware = sdc.helpers.getExpressMiddleware({
  timeByUrl: true
});

  const app = express();
  app.disable('x-powered-by');
  app.use(cors);
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({extended: true}));
  app.use(metricsMiddleware);
```

**Comment by msiebuhr** [comment]
Can you try switching to `v0.2.0` and see if it's still there?

(There's been some changes there recently, and the code isn't really tested on a systematic basis.)

**Comment by msiebuhr** [comment]
Right. Tried poking a bit at it, but I can't just now see a way to make it output `[object Object]`. Mind dumping a few `console.log()`'s in `lib/helpers/getExpressMiddleware.js`?

I've hacked some quick tests in 34b44ca, where you can toy around. (Also, I wouldn't mind a failing test case, if you figure it out :smile: )

**Comment by lumberj** [comment]
0.2.0 is working as expected
