### ISSUE TITLE
EphemeralSocket logging is commented out

### ISSUE THREAD

**Issue by danihodovic** [msiebuhr/node-statsd-client#57]
https://github.com/msiebuhr/node-statsd-client/blob/master/lib/EphemeralSocket.js#L24

Is there any purpose behind this? Ideally you should be able to log and debug what's going on when debug is set to true.

**Comment by msiebuhr** [comment]
I guess it's a bad habit of mine - I generally do `printf`-debugging, so I left that in as a shortcut.

Given that metrics are generally used as a separate thing from logging, I don't see any purpose in adding any general logging-output of the metrics. But if you feel it's useful for debugging, I guess emitting events shouldn't be too much overhead.
