### ISSUE TITLE
set() doesn't track uniques

### ISSUE THREAD

**Issue by garthk** [msiebuhr/node-statsd-client#61]
What I expected:

```js
statsd.set('names', 'A');
statsd.set('names', 'B');
statsd.set('names', 'C');
```

… with `names:3|s` emitted. 

Instead, I need to `statsd.set('names', 3)`… in which case, keeping track of the set and when to emit is left to me.

**Comment by garthk** [comment]
[`armon/statsite`](https://github.com/armon/statsite#protocol) suggests we're supposed to send raw values. I'll chase it up in this [proposed spec change](https://github.com/mrtazz/statsd_spec/commit/6172d39).

**Comment by msiebuhr** [comment]
I think you've got it wrong. The point of sets is that they count uniques across several clients reporting to the same statsd-server. Example:

Client one sends `A` and `B`, while client two sends `B` and `C`. The total set has size 3, which only the server can deduce. (It can't if it only gets `2` and `2` sent....)

(That being said, the client could be some more intelligent about de-duplicating the sending of multiple keys in one packet.)
