### ISSUE TITLE
StatsD Ephemeral Socket client stops sending metrics on server restart

### ISSUE THREAD

**Issue by jasonmoo** [msiebuhr/node-statsd-client#64]
Hi.  Currently experiencing an issue where when our statsd collector is restarted, it stops receiving metrics from all clients until they are restarted.

I looked through the code and found a curious spot.

https://github.com/msiebuhr/node-statsd-client/blob/master/lib/EphemeralSocket.js#L117-L120

Why does the client bind to a socket and listen for udp packets before sending them?

**Comment by msiebuhr** [comment]
I haven't touched that code in quite a while, so I can't quite argument for all the decisions. Looks like 7f58aa00ef8a90a791d05a8efe926bda62cbfb03 at least has some explanations for why things are done that way...

**Comment by papandreou** [comment]
It should be possible to simulate this in a test case?

**Comment by msiebuhr** [comment]
We could kill the test-server while the test-client is running. But I'm leaning more towards just removing the `bind()` call, as it doesn't add anything useful AFAIK.
