### ISSUE TITLE
are express routes in form of arrays supported?

### ISSUE THREAD

**Issue by ptrwllrt** [msiebuhr/node-statsd-client#71]
Just tried to define routes like: 
```
.get(
      [ '/aroute', '/broute', '/croute'],
      (req, res, next) => doAThing();
    )
```
According to http://expressjs.com/de/api.html#path-examples arrays are supported. Sadly I get an error in here: https://github.com/msiebuhr/node-statsd-client/blob/master/lib/helpers/getExpressMiddleware.js#L4

**Comment by msiebuhr** [comment]
Wow. I vaguely remember seeing it, but never looked further into it.

As you get an error, we obviously don't support it. Feel free to make a patch for it.
