### ISSUE TITLE
Tag format incompatible with Telegraf

### ISSUE THREAD

**Issue by acanimal** [msiebuhr/node-statsd-client#81]
Hi,
I'm using this library to send data to telegraf-statsd server. All seems to work fine except when I attach tags to the metrics.

Given this sentence `sdc.increment('my_counter', 2, { service: 'value' });`  the library send the message `my_counter:2|c|#service:value` while telegraf-statsd expects something like `my_counter,service=value:+3|c`.

Does the library supports telegraf?

**Comment by msiebuhr** [comment]
Unfortunately, we don't.

ATM, the output formatting is pretty hard-coded (ex. https://github.com/msiebuhr/node-statsd-client/blob/master/lib/statsd-client.js#L126-L144).

Perhaps have a look at [hot-shots](https://www.npmjs.com/package/hot-shots) which has a similar (*almost* drop-in) API and telegraf support.

**Comment by tscruggs** [comment]
> Given this sentence sdc.increment('my_counter', 2, { service: 'value' }); the library send the message my_counter:2|c|#service:value while telegraf-statsd expects something like my_counter,service=value:+3|c.

The above message format actually works fine with the Telegraf statsd input so long as you have the `datadog_extensions` enabled as described [here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/README.md). Verified with version 1.14.0.
