### ISSUE TITLE
Are there any ways to make sure statsdclient is working?

### ISSUE THREAD

**Issue by chiro-hiro** [msiebuhr/node-statsd-client#89]
I'm expecting statsclient could emit some events that would help developers to observer its status.

E.g:

```ts
sdc.on('connect', (): void=>{});
sdc.on('data', (): void=>{});
sdc.on('error', (): void=> {});
sdc.on('close', (): void=>{});
```

**Comment by msiebuhr** [comment]
It's sending UDP data; once data hits the kernel/network, there is no guarantees that data will actually arrive.
